---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: dask-scheduler-{{ template "arl-cluster.fullname" . }}
  labels:
    app: dask-scheduler-{{ template "arl-cluster.fullname" . }}
    chart: {{ template "arl-cluster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    # k8s-app: dask-scheduler-{{ template "arl-cluster.fullname" . }}
spec:
  type: {{ .Values.daskscheduler.service.type }}
  ports:
  - name: scheduler
    port: {{ .Values.daskscheduler.service.scheduler.port }}
    targetPort: scheduler
    protocol: TCP
  - name: bokeh
    port: {{ .Values.daskscheduler.service.bokeh.port }}
    targetPort: bokeh
    protocol: TCP
  selector:
    # k8s-app: dask-scheduler-{{ template "arl-cluster.name" . }}
    app: dask-scheduler-{{ template "arl-cluster.name" . }}
    release: {{ .Release.Name }}
