---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: notebook-{{ template "arl-cluster.fullname" . }}
  labels:
    app: notebook-{{ template "arl-cluster.fullname" . }}
    chart: {{ template "arl-cluster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    # k8s-app: notebook-{{ template "arl-cluster.fullname" . }}
spec:
  type: {{ .Values.notebook.service.type }}
  ports:
  - name: jupyter
    port: {{ .Values.notebook.service.jupyter.port }}
    targetPort: jupyter
    protocol: TCP
  selector:
    # k8s-app: notebook-{{ template "arl-cluster.name" . }}
    app: notebook-{{ template "arl-cluster.name" . }}
    release: {{ .Release.Name }}
